function M = calc_M(in1,in2)
%calc_M
%    M = calc_M(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    21-Jan-2025 15:28:29

K1_I1 = in2(6,:);
K2_I2 = in2(7,:);
alpha = in1(1,:);
beta = in1(2,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(3,:);
m2 = in2(4,:);
t2 = cos(alpha);
t3 = cos(beta);
t4 = sin(alpha);
t5 = sin(beta);
t6 = l1.^2;
t7 = l2.^2;
t8 = t2.^2;
t9 = t4.^2;
t10 = beta.*t2;
t11 = l1.*t2;
t12 = l1.*t4;
t13 = t4.*t5;
t14 = t2.*t3;
t15 = t2.*t5;
t16 = t3.*t4;
t17 = t10+1.0;
t18 = -t14;
t19 = t15+t16;
t20 = t13+t18;
t21 = t2.*t19;
t22 = t4.*t19;
t24 = (l2.*t19)./2.0;
t31 = t17.*t19;
t23 = beta.*t22;
t25 = t2.*t20;
t26 = t4.*t20;
t30 = (l2.*t20)./2.0;
t32 = t17.*t20;
t33 = t11+t24;
t28 = beta.*t26;
t34 = t12+t30;
t35 = t21+t26;
t38 = m2.*t24.*t33;
t44 = -K2_I2.*t20.*(t22-t25);
t49 = -K2_I2.*t20.*(t23-t32);
t37 = t28+t31;
t40 = m2.*t30.*t34;
t41 = K2_I2.*t19.*t35;
t43 = K2_I2.*t20.*t35;
t46 = K2_I2.*t19.*t37;
t48 = K2_I2.*t20.*t37;
t51 = t41+t44;
t53 = t46+t49;
M = reshape([K1_I1.*t8+K1_I1.*t9+t17.*t53+m2.*t33.^2+m2.*t34.^2+(m1.*t6.*t8)./4.0+(m1.*t6.*t9)./4.0+beta.*t4.*(t48+K2_I2.*t19.*(t23-t32)),t38+t40+t17.*(t43+K2_I2.*t19.*(t22-t25))-beta.*t4.*t51,t38+t40+t4.*t53-t2.*(t48+K2_I2.*t19.*(t23-t32)),t2.*t51+t4.*(t43+K2_I2.*t19.*(t22-t25))+(m2.*t7.*t19.^2)./4.0+(m2.*t7.*t20.^2)./4.0],[2,2]);
end
