function D = calc_D(in1,in2,in3)
%calc_D
%    D = calc_D(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Jan-2025 22:41:58

alpha = in1(1,:);
alpha_dot = in2(1,:);
beta = in1(2,:);
beta_dot = in2(2,:);
l1 = in3(1,:);
l2 = in3(2,:);
m2 = in3(4,:);
t2 = cos(alpha);
t3 = cos(beta);
t4 = sin(alpha);
t5 = sin(beta);
t6 = l1.*t2;
t7 = l1.*t4;
t8 = t4.*t5;
t9 = t2.*t3;
t10 = t2.*t5;
t11 = t3.*t4;
t12 = -t9;
t13 = t10+t11;
t14 = t8+t12;
t15 = (l2.*t13)./2.0;
t16 = (l2.*t14)./2.0;
t17 = t6+t15;
t18 = t7+t16;
t23 = -alpha_dot.*((l2.*m2.*t13.*t18)./2.0-(l2.*m2.*t14.*t17)./2.0);
t25 = beta_dot.*((l2.*m2.*t13.*t18)./2.0-(l2.*m2.*t14.*t17)./2.0);
D = reshape([t23,t25,alpha_dot.*((l2.*m2.*t13.*t18)./2.0-(l2.*m2.*t14.*t17)./2.0),t25],[2,2]);
end
