function x0 = calc_x0(t)
%CALC_X0
%    X0 = CALC_X0(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    16-Jan-2025 19:13:22

x0 = reshape([t.*(-2.565767314538405),t.*2.465452051359372e-1,t.*(-3.55706166485363e-3),t.*2.034951361333008e-3],[2,2]);
end
